### ISSUE TITLE
Burp 2.0 (beta) added new tab "Dashboard"

### ISSUE THREAD

**Issue by mgeeky** [hvqzao/burp-wildcard#2]
Hello there,

The extension in question behaves incorrectly by hiding Dashboard tab of Burpsuite's where it shouldn't do that. Also, there are times when the extension after disabling it's work through it's options pane - does not unhide that Dashboard tab leaving Burp without it completely, until restarted.

**Comment by hvqzao** [comment]
Hi, new release should address your issue - https://github.com/hvqzao/burp-wildcard/releases/tag/v1.05
