### ISSUE TITLE
The latest version does not have the Nimbus theme anymore

### ISSUE THREAD

**Issue by theblackturtle** [hvqzao/burp-wildcard#5]
Hi, 

In some releases recently, they don't use the Nimbus/Dracula theme, etc anymore. Only Dark/Light available now. Can you fix this problem, please? Thanks.

**Comment by hvqzao** [comment]
Hi, I've just submitted updated build to Portswigger BApp Store.

**Comment by hvqzao** [comment]
Hi, sorry, I assumed you are talking about Flow extension, Wildcard will never be accepted by Portswigger. I've updated Wildcard to also work with new release. You can build it from newest sources or download from here: https://github.com/hvqzao/burp-wildcard/releases/tag/1.08
Best wishes in 2021!
